import { v4 as uuidv4 } from "uuid";

const ListaProdutos = [
  {
    id: uuidv4(),
    nome: "Misto-Quente",
    avaliacao: 4.8,
    imagem: "/images/produtos/misto-quente.svg",
    preco: 10,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Chocolate Quente",
    avaliacao: 4.8,
    imagem: "/images/produtos/chocolate-quente.svg",
    preco: 8,
    vendas: 5,
  },
  {
    id: uuidv4(),
    nome: "Café com Sorvete",
    avaliacao: 4.8,
    imagem: "/images/produtos/cafe-com-sorvete.svg",
    preco: 10,
    vendas: 5,
  },
  {
    id: uuidv4(),
    nome: "Chá Matte",
    avaliacao: 4.8,
    imagem: "/images/produtos/cha-matte.svg",
    preco: 6,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Cappucino",
    avaliacao: 4.8,
    imagem: "/images/produtos/cappucino.svg",
    preco: 8,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Moccacinno",
    avaliacao: 4.8,
    imagem: "/images/produtos/moccacinno.svg",
    preco: 9,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Waffle com Sorvete",
    avaliacao: 4.8,
    imagem: "/images/produtos/waffle-com-sorvete.svg",
    preco: 15,
    vendas: 10,
  },
  {
    id: uuidv4(),
    nome: "Coxinha",
    avaliacao: 4.8,
    imagem: "/images/produtos/coxinha.svg",
    preco: 8,
    vendas: 8,
  },
  {
    id: uuidv4(),
    nome: "Salada",
    avaliacao: 4.8,
    imagem: "/images/produtos/salada.svg",
    preco: 12,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Brownnie",
    avaliacao: 4.8,
    imagem: "/images/produtos/brownnie.svg",
    preco: 6,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Água Gelada",
    avaliacao: 4.8,
    imagem: "/images/produtos/agua-gelada.svg",
    preco: 6,
    vendas: 0,
  },
  {
    id: uuidv4(),
    nome: "Refrigerante",
    avaliacao: 4.8,
    imagem: "/images/produtos/refrigerante.svg",
    preco: 5,
    vendas: 0,
  },
];

export default ListaProdutos;
